<?php
/**
 * Git Remote Deploy
 *
 * Copyright 2019-2020 leo <2579186091@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace app\queue;

use app\lib\base;
use ext\conf;
use ext\queue;
use ext\redis;

class master extends queue
{
    public $tz = ['start', 'unit'];

    /**
     * master constructor.
     */
    public function __construct()
    {
        parent::__construct(redis::create(conf::get('redis'))->connect());
    }

    /**
     * 最多启动4个子进程
     *
     * @param int $max_fork
     * @param int $max_exec
     *
     * @throws \Exception
     */
    public function start(int $max_fork = 12, int $max_exec = 1000): void
    {
        $this->set_name('gitRemoteDeploy')->go($max_fork, $max_exec); // TODO: Change the autogenerated stub
    }
}
